[pytest]
pythonpath = .
testpaths = tests
addopts = -ra --basetemp=.pytest_tmp
filterwarnings =
    ignore:vert.*:matplotlib.MatplotlibDeprecationWarning
    ignore:The set_bad function.*:PendingDeprecationWarning
