services:
  - type: web
    name: laliga-predictor-grupo4
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./docker/backend.Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: off
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: laliga-predictor-grupo4-db
          property: connectionString
      - key: AUTH_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        sync: false

databases:
  - name: laliga-predictor-grupo4-db
    plan: free
    region: frankfurt
    databaseName: laliga
    user: laliga
